const GET_TAG_REQUEST = 'GET_TAG_REQUEST';
const GET_TAG_SUCCESS = 'GET_TAG_SUCCESS';
const GET_TAG_ERROR = 'GET_TAG_ERROR';

export default {
  GET_TAG_REQUEST,
  GET_TAG_SUCCESS,
  GET_TAG_ERROR,
};
